# Root directory for the project
root = "."

# Temporary directory for compiled binaries
tmp_dir = "tmp"

# Build configuration
[build]
bin = "./tmp/main"                     # Path to the binary file
cmd = "go build -o ./tmp/main main.go" # Build command
delay = 1000                           # Delay in milliseconds before rebuilding after a change
exclude_dir = ["assets", "tmp", "vendor", "docker", "bin"] # Directories to exclude from watching
include_ext = ["go", "tpl", "tmpl", "html"]                # File extensions to watch for changes
kill_delay = "0s"                       # Delay before killing the process
log = "build-errors.log"                # Log file for build errors
stop_on_error = true                    # Stop on build error
full_bin = "APP_ENV=development ./tmp/main" # Command to run the binary with environment variables

# Color configuration for logs
[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

# Log configuration
[log]
time = true

# Miscellaneous configuration
[misc]
clean_on_exit = false
